---
- name: "Setup customizations: Activation Key"
  when: image_builder_activation_key is defined
  ansible.builtin.set_fact:
    image_builder_subscription:
      activation-key: "{{ image_builder_activation_key }}"
      insights: "{{ image_builder_insights_enabled }}"
      rhc: "{{ image_builder_rhc_enabled }}"
      server-url: "subscription.rhsm.redhat.com"
      base-url: "https://cdn.redhat.com/"
      organization: "{{ image_builder_organization_id }}"

- name: "Setup customizations: default"
  when: image_builder_customizations is not defined
  ansible.builtin.set_fact:
    image_builder_customizations:
      packages: "{{ image_builder_image_packages }}"
      filesystem: "{{ image_builder_custom_filesystem }}"
      subscription: "{{ image_builder_subscription | default(omit) }}"
      users: "{{ image_builder_users | default(omit) }}"
...
