---

- name: Get access token
  ansible.builtin.uri:
    method: POST
    body:
      grant_type: refresh_token
      client_id: rhsm-api
      refresh_token: "{{ image_builder_rhsm_offline_token | default(lookup('env', 'REDHAT_API_OFFLINE_TOKEN')) }}"
    body_format: form-urlencoded
    url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
  register: image_builder_access_token_request

- name: Set fact for access token
  ansible.builtin.set_fact:
    image_builder_rhsm_access_token: "{{ image_builder_access_token_request.json.access_token }}"


# check for existing compose jobs
# if one exists with name == image_builder_image_name, set facts for compose id and create date
# skip if image_builder_force_create is set to true
- name: Check for matching existing compose jobs
  when: not image_builder_force_create
  block:
    - name: Get existing compose jobs
      ansible.builtin.uri:
        headers:
          Authorization: "Bearer {{ image_builder_rhsm_access_token }}"
        url: "https://console.redhat.com/api/image-builder/v1/composes"
      register: image_builder_existing_composes

    - name: Set fact for first existing compose id/create timestamp
      ansible.builtin.set_fact:
        image_builder_compose_id: "{{ image_builder_existing_composes.json | community.general.json_query(image_builder_name_query) }}"
        image_builder_first_matching_compose_created_at: "{{ image_builder_existing_composes.json | community.general.json_query(image_builder_create_query) }}"
      vars:
        image_builder_name_query: "data[?image_name=='{{ image_builder_image_name }}'].id | [0]"
        image_builder_create_query: "data[?image_name=='{{ image_builder_image_name }}'].created_at | [0]"

    # had to do this separate because it relies on a fact from above
    - name: Set fact for first existing compose elapsed time
      when: image_builder_compose_id | length > 0
      ansible.builtin.set_fact:
        image_builder_first_matching_compose_elapsed_seconds: "{{ (now(true) - (image_builder_first_matching_compose_created_at | to_datetime(image_builder_datetime_format))).seconds }}"
      vars:
        image_builder_datetime_format: "%Y-%m-%dT%H:%M:%SZ"

# build new image if:
# existing image is expired
# image_builder_force_create is set to true
# no existing image exists
- name: Build new image
  when: image_builder_force_create or
        (image_builder_compose_id | length == 0) or
        (image_builder_first_matching_compose_elapsed_seconds is defined and (image_builder_first_matching_compose_elapsed_seconds | int) > image_builder_max_elapsed)
  block:
    # import upload request tasks
    - name: Setup upload request
      ansible.builtin.import_tasks:
        file: upload_request.yml

    # import customization tasks
    - name: Setup customizations
      ansible.builtin.import_tasks:
        file: customizations.yml

    - name: Prepare request body
      ansible.builtin.set_fact:
        image_builder_post_body:
          distribution: "{{ image_builder_distribution }}"
          image_name: "{{ image_builder_image_name }}"
          image_requests:
            - architecture: "{{ image_builder_architecture }}"
              image_type: "{{ image_builder_image_type }}"
              upload_request: "{{ image_builder_upload_request }}"
          customizations: "{{ image_builder_customizations }}"

    - name: Print request body
      ansible.builtin.debug:
        msg: "{{ image_builder_post_body }}"

    - name: Start build process
      ansible.builtin.uri:
        method: POST
        body: "{{ image_builder_post_body }}"
        body_format: json
        url: https://console.redhat.com/api/image-builder/v1/compose
        headers:
          Authorization: "Bearer {{ image_builder_rhsm_access_token }}"
        status_code: 201
      register: image_builder_compose_response

    - name: Set fact for image id
      ansible.builtin.set_fact:
        image_builder_compose_id: "{{ image_builder_compose_response.json.id }}"

# get initial compose status
- name: Check status of existing compose
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ image_builder_rhsm_access_token }}"
    url: "https://console.redhat.com/api/image-builder/v1/composes/{{ image_builder_compose_id }}"
  register: image_builder_compose_status

# wait for pending and update status var if necessary
- name: Handle pending status
  when: image_builder_compose_status.json.image_status.status == "pending"
  block:
    - name: Build is pending, waiting for next stage
      ansible.builtin.uri:
        headers:
          Authorization: "Bearer {{ image_builder_rhsm_access_token }}"
        url: "https://console.redhat.com/api/image-builder/v1/composes/{{ image_builder_compose_id }}"
      register: image_builder_compose_pending
      until: image_builder_compose_pending.json.image_status.status != "pending"
      retries: "{{ image_builder_retries }}"
      delay: 30

    - name: Set fact for image id
      ansible.builtin.set_fact:
        image_builder_compose_status: "{{ image_builder_compose_pending }}"

# wait for building and update status var if necessary
- name: Handle building status
  when: image_builder_compose_status.json.image_status.status == "building"
  block:
    - name: Image is building, waiting for next stage
      ansible.builtin.uri:
        headers:
          Authorization: "Bearer {{ image_builder_rhsm_access_token }}"
        url: "https://console.redhat.com/api/image-builder/v1/composes/{{ image_builder_compose_id }}"
      register: image_builder_compose_building
      until: image_builder_compose_building.json.image_status.status != "building"
      retries: "{{ image_builder_retries }}"
      delay: 30

    - name: Set fact for image id
      ansible.builtin.set_fact:
        image_builder_compose_status: "{{ image_builder_compose_building }}"

- name: Get meta data
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ image_builder_rhsm_access_token }}"
    url: "https://console.redhat.com/api/image-builder/v1/openapi.json"
