---
- name: Gather packages facts
  package_facts:

- name: Create Image Builder configuration directory
  file:
    path: "{{ image_builder_cli_repo_path }}"
    state: directory
    mode: '0755'
  when: image_builder_cli_use_satellite | bool

- name: Read system repository configuration
  vars:
    rhel_ver: "{{ ansible_facts.distribution_major_version }}"
    rhel_arch: "{{ ansible_facts.architecture }}"
  shell: >
    set -o pipefail &&
    grep -A 5 '^\[rhel-{{ rhel_ver }}-for-{{ rhel_arch }}-baseos-rpms\]' /etc/yum.repos.d/redhat.repo
    | awk '/baseurl/ {print $3}'
  register: rhsm_baseurl
  changed_when: false
  when:
    - image_builder_cli_use_satellite | bool
    - image_builder_cli_repo_versions | default(false, true)

- name: Create basic repository configuration files
  vars:
    baseos_repo_url: "{{ rhsm_baseurl.stdout | replace('$releasever', item) }}"
    appstream_repo_url: "{{ rhsm_baseurl.stdout | replace('$releasever', item) | replace('baseos', 'appstream') }}"
  template:
    src: rhel-repo.json.j2
    dest: "{{ image_builder_cli_repo_path }}/rhel-{{ item }}.json"
    mode: '0644'
  register: config_basic
  loop: "{{ image_builder_cli_repo_versions | default([], true) }}"
  when: image_builder_cli_use_satellite | bool

- name: Create custom repository configuration files
  template:
    src: "{{ item }}"
    dest: "{{ image_builder_cli_repo_path }}/{{ item | basename | replace('.j2', '') }}"
    mode: '0644'
  register: config_custom
  loop: "{{ image_builder_cli_repo_templates | default([], true) }}"
  when: image_builder_cli_use_satellite | bool

- name: Reboot system
  reboot:
  when:
    - "'osbuild-composer' in ansible_facts.packages"
    - config_basic is changed or
      config_custom is changed

- name: Install Podman
  dnf:
    name:
      - git-core
      - podman
    state: present
  register: builder_packages
  when:
    - "'git-core' not in ansible_facts.packages"
    - "'podman' not in ansible_facts.packages"

- name: Update all packages
  # noqa: package-latest
  dnf:
    name: '*'
    state: latest
    update_cache: true
  register: package_update
  when: image_builder_cli_update_host | bool

- name: Reboot system
  reboot:
  when:
    - image_builder_cli_reboot_host | bool
    - builder_packages is changed or
      package_update is changed

- name: Pull the image-builder container
  containers.podman.podman_image:
    name: ghcr.io/osbuild/image-builder-cli
    tag: "{{ image_builder_cli_version }}"
