---
- name: Update output directory permissions
  ansible.builtin.file:
    path: "{{ image_builder_cli_output_path }}"
    mode: '0750'
    recurse: true
  when: "'SUDO_USER' in ansible_facts.env"

- name: Update output file permissions
  ansible.builtin.file:
    path: "{{ image_builder_cli_output_path }}"
    owner: "{{ ansible_facts.env.SUDO_USER }}"
    mode: '0600'
    recurse: true
  when: "'SUDO_USER' in ansible_facts.env"

- name: Find files on build host to fetch
  ansible.builtin.find:
    paths: "{{ image_builder_cli_output_path }}"
    recurse: true
  register: image_builder_files_to_fetch

- name: Fetch image file from build host
  become: false # do not remove this
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: "{{ image_builder_cli_fetch_directory }}/"
    flat: true
  with_items: "{{ image_builder_files_to_fetch.files }}"

- name: Remove output dir on build host
  ansible.builtin.file:
    path: "{{ image_builder_cli_output_path }}"
    state: absent
  when: image_builder_cli_remote_delete | bool

- name: Print build artifacts
  ansible.builtin.debug:
    msg: "Fetched the following files into {{ image_builder_cli_fetch_directory }}:\n{{ image_builder_files_to_fetch.files | map(attribute='path') | list }}"
