---
- name: Setup Image Builder
  ansible.builtin.include_tasks: builder_setup.yml
  when: image_builder_cli_do_setup | bool

- name: Build image
  ansible.builtin.include_tasks: build_image.yml
  when: image_builder_cli_do_build | bool

- name: Fetch image
  ansible.builtin.include_tasks: fetch_image.yml
  when: image_builder_cli_fetch_image | bool
